### ISSUE TITLE
OMG!! 70MB on clone :O

### ISSUE THREAD

**Issue by addy-dclxvi** [dylanaraps/dotfiles#7]
Hello Sir!
Very cool collection of dotfiles, I love it.
But, may I ask?
Why the download size is so massive for 30KB dotfiles?

**Comment by dylanaraps** [comment]
Add `--depth 1` to `git clone`.

This repo contains almost 3 years of data. `--depth 1` makes `git` only download the most recent version.

**Comment by addy-dclxvi** [comment]
Thank You very much!!

**Comment by dylanaraps** [comment]
I’ll add something to the README about this. :)
