### ISSUE TITLE
It appears your hyperlink to the screenshots is 404ing

### ISSUE THREAD

**Issue by oidz1234** [dylanaraps/dotfiles#8]

**Comment by dylanaraps** [comment]
The website is under construction, here are imgur links.

- https://i.imgur.com/AoME7yC.png
- https://imgur.com/a/mZtHh
- https://i.imgur.com/hkAJjJg.png
- https://imgur.com/a/DbeOy

**Comment by oidz1234** [comment]
thanks

**Comment by dylanaraps** [comment]
Keeping this open for clarity.
