### ISSUE TITLE
Stowing home would cause conflicts

### ISSUE THREAD

**Issue by Pablecito** [dylanaraps/dotfiles#9]
Hi ! First, your dotfiles are amazing !

I hope I did nothing wrong (Trying my first linux distro, really a noob).
So, I'm on Manjaro at the moment. I started the install.sh and got this :

install cmus? [y/n] y
install dunst? [y/n] y
install home? [y/n] y
WARNING! stowing home would cause conflicts:
  * existing target is neither a link nor a directory: .Xresources
  * existing target is neither a link nor a directory: .bashrc
  * existing target is neither a link nor a directory: .xinitrc
All operations aborted.

**Comment by dylanaraps** [comment]
Not a bug. The install script/stow won't overwrite your existing files.
